# This workflow runs ESLint to enforce code style and catch potential issues.

name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: .bun-version
    - run: bun install --frozen-lockfile
    - run: bun run lint
